# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: completions.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'completions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63ompletions.proto\x12\x0c\x61utocomplete\"\'\n\x16\x43ompletionRequestProto\x12\r\n\x05query\x18\x01 \x01(\t\"o\n\x13\x43ompletionItemProto\x12\x13\n\x0bsentence_id\x18\x01 \x01(\x03\x12\x1a\n\x12\x63ompleted_sentence\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x05\x12\x18\n\x10occurrence_count\x18\x04 \x01(\x05\"\x8e\x01\n\x17\x43ompletionResponseProto\x12\r\n\x05query\x18\x01 \x01(\t\x12\x18\n\x10normalized_query\x18\x02 \x01(\t\x12\x12\n\nelapsed_ms\x18\x03 \x01(\x01\x12\x36\n\x0bsuggestions\x18\x04 \x03(\x0b\x32!.autocomplete.CompletionItemProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'completions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMPLETIONREQUESTPROTO']._serialized_start=35
  _globals['_COMPLETIONREQUESTPROTO']._serialized_end=74
  _globals['_COMPLETIONITEMPROTO']._serialized_start=76
  _globals['_COMPLETIONITEMPROTO']._serialized_end=187
  _globals['_COMPLETIONRESPONSEPROTO']._serialized_start=190
  _globals['_COMPLETIONRESPONSEPROTO']._serialized_end=332
# @@protoc_insertion_point(module_scope)
